const tvkList = [
  {
    constituencyNo: 1,
    constituencyName: "Gummidipoondi",
    candidateName: "S. Vijayakumar",
    district: "Tiruvallur",
  },
  {
    constituencyNo: 2,
    constituencyName: "Ponneri",
    candidateName: "Dr. M.S. Ravi",
    district: "Tiruvallur",
  },
  {
    constituencyNo: 3,
    constituencyName: "Tiruttani",
    candidateName: "Dr. M. Sathiyakumar",
    district: "Tiruvallur",
  },
  {
    constituencyNo: 4,
    constituencyName: "Thiruvallur",
    candidateName: "Dr. T. Arunkumar",
    district: "Tiruvallur",
  },
  {
    constituencyNo: 5,
    constituencyName: "Poonamallee",
    candidateName: "R. Prakash",
    district: "Tiruvallur",
  },
  {
    constituencyNo: 6,
    constituencyName: "Avadi",
    candidateName: "R. Ramesh Kumar",
    district: "Tiruvallur",
  },
  {
    constituencyNo: 7,
    constituencyName: "Maduravoyal",
    candidateName: "P. Revanth Charan",
    district: "Chennai",
  },
  {
    constituencyNo: 8,
    constituencyName: "Ambattur",
    candidateName: "G. Balamurugan",
    district: "Chennai",
  },
  {
    constituencyNo: 9,
    constituencyName: "Madhavaram",
    candidateName: "M.L. Vijayaprabhu",
    district: "Chennai",
  },
  {
    constituencyNo: 10,
    constituencyName: "Thiruvottiyur",
    candidateName: "N. Senthil Kumar",
    district: "Chennai",
  },
  {
    constituencyNo: 11,
    constituencyName: "RK Nagar",
    candidateName: "Dr. N. Mariya Wilson",
    district: "Chennai",
  },
  {
    constituencyNo: 12,
    constituencyName: "Perambur",
    candidateName: "C. Joseph Vijay",
    district: "Chennai",
  },
  {
    constituencyNo: 13,
    constituencyName: "Kolathur",
    candidateName: "V.S. Babu",
    district: "Chennai",
  },
  {
    constituencyNo: 14,
    constituencyName: "Villivakkam",
    candidateName: "Adhav Arjuna",
    district: "Chennai",
  },
  {
    constituencyNo: 15,
    constituencyName: "Thiru-Vi-Ka-Nagar",
    candidateName: "M.R. Pallavi",
    district: "Chennai",
  },
  {
    constituencyNo: 16,
    constituencyName: "Egmore",
    candidateName: "A. Rajmohan",
    district: "Chennai",
  },
  {
    constituencyNo: 17,
    constituencyName: "Royapuram",
    candidateName: "K.V. Vijay Ramu",
    district: "Chennai",
  },
  {
    constituencyNo: 18,
    constituencyName: "Harbour",
    candidateName: "Senora P.S. Ashok",
    district: "Chennai",
  },
  {
    constituencyNo: 19,
    constituencyName: "Chepauk",
    candidateName: "D. Selvam",
    district: "Chennai",
  },
  {
    constituencyNo: 20,
    constituencyName: "Thousand Lights",
    candidateName: "JCD. Prabhakar",
    district: "Chennai",
  },
  {
    constituencyNo: 21,
    constituencyName: "Anna Nagar",
    candidateName: "V.K. Ramkumar",
    district: "Chennai",
  },
  {
    constituencyNo: 22,
    constituencyName: "Virugambakkam",
    candidateName: "R. Harinathan",
    district: "Chennai",
  },
  {
    constituencyNo: 23,
    constituencyName: "Saidapet",
    candidateName: "M. Arul Prakasam",
    district: "Chennai",
  },
  {
    constituencyNo: 24,
    constituencyName: "T. Nagar",
    candidateName: "N. Anand",
    district: "Chennai",
  },
  {
    constituencyNo: 25,
    constituencyName: "Mylapore",
    candidateName: "P. Venkataramanan",
    district: "Chennai",
  },
  {
    constituencyNo: 26,
    constituencyName: "Velachery",
    candidateName: "R. Kumar",
    district: "Chennai",
  },
  {
    constituencyNo: 27,
    constituencyName: "Sholinganallur",
    candidateName: "P. Saravanamurthi",
    district: "Chennai",
  },
  {
    constituencyNo: 28,
    constituencyName: "Alandur",
    candidateName: "M. Harish",
    district: "Chennai",
  },
  {
    constituencyNo: 29,
    constituencyName: "Sriperumbudur",
    candidateName: "K. Thennarasu",
    district: "Kanchipuram",
  },
  {
    constituencyNo: 30,
    constituencyName: "Pallavaram",
    candidateName: "J. Kamatchi",
    district: "Chengalpattu",
  },
  {
    constituencyNo: 31,
    constituencyName: "Tambaram",
    candidateName: "D. Sarath Kumar",
    district: "Chengalpattu",
  },
  {
    constituencyNo: 32,
    constituencyName: "Chengalpattu",
    candidateName: "S. Thiagarajan",
    district: "Chengalpattu",
  },
  {
    constituencyNo: 33,
    constituencyName: "Tiruporur",
    candidateName: "B. Vijayaraj",
    district: "Chengalpattu",
  },
  {
    constituencyNo: 34,
    constituencyName: "Cheyyur",
    candidateName: "K. Mohanraja",
    district: "Chengalpattu",
  },
  {
    constituencyNo: 35,
    constituencyName: "Maduranthakam",
    candidateName: "E. Ezhil Cathrine",
    district: "Chengalpattu",
  },
  {
    constituencyNo: 36,
    constituencyName: "Uthiramerur",
    candidateName: "J. Munirathinam",
    district: "Kanchipuram",
  },
  {
    constituencyNo: 37,
    constituencyName: "Kancheepuram",
    candidateName: "R.V. Ranjith Kumar",
    district: "Kanchipuram",
  },
  {
    constituencyNo: 38,
    constituencyName: "Arakkonam",
    candidateName: "V. Kanthiraj",
    district: "Ranipet",
  },
  {
    constituencyNo: 39,
    constituencyName: "Sholingur",
    candidateName: "Dr. G. Kapil",
    district: "Ranipet",
  },
  {
    constituencyNo: 40,
    constituencyName: "Katpadi",
    candidateName: "Dr. M. Sudhakar",
    district: "Vellore",
  },
  {
    constituencyNo: 41,
    constituencyName: "Ranipet",
    candidateName: "I. Tahira",
    district: "Ranipet",
  },
  {
    constituencyNo: 42,
    constituencyName: "Arcot",
    candidateName: "G. Vijay Mohan",
    district: "Ranipet",
  },
  {
    constituencyNo: 43,
    constituencyName: "Vellore",
    candidateName: "M.M. Vinoth Kannan",
    district: "Vellore",
  },
  {
    constituencyNo: 44,
    constituencyName: "Anaicut",
    candidateName: "R. Velmurugan",
    district: "Vellore",
  },
  {
    constituencyNo: 45,
    constituencyName: "KV Kuppam",
    candidateName: "E. Thenral Kumar",
    district: "Vellore",
  },
  {
    constituencyNo: 46,
    constituencyName: "Gudiyattam",
    candidateName: "K. Sindhu",
    district: "Vellore",
  },
  {
    constituencyNo: 47,
    constituencyName: "Vaniyambadi",
    candidateName: "S. Syed Burhanuddin",
    district: "Tirupattur",
  },
  {
    constituencyNo: 48,
    constituencyName: "Ambur",
    candidateName: "P. Imthiyaz",
    district: "Tirupattur",
  },
  {
    constituencyNo: 49,
    constituencyName: "Jolarpet",
    candidateName: "C. Munisamy",
    district: "Tirupattur",
  },
  {
    constituencyNo: 50,
    constituencyName: "Tirupattur",
    candidateName: "Dr. N. Tirupathi",
    district: "Tirupattur",
  },
  {
    constituencyNo: 51,
    constituencyName: "Uthangarai",
    candidateName: "P. Kumaravel",
    district: "Krishnagiri",
  },
  {
    constituencyNo: 52,
    constituencyName: "Bargur",
    candidateName: "E. Muralidharan",
    district: "Krishnagiri",
  },
  {
    constituencyNo: 53,
    constituencyName: "Krishnagiri",
    candidateName: "P. Mugunthan",
    district: "Krishnagiri",
  },
  {
    constituencyNo: 54,
    constituencyName: "Veppanahalli",
    candidateName: "S.R. Sampangi",
    district: "Krishnagiri",
  },
  {
    constituencyNo: 55,
    constituencyName: "Hosur",
    candidateName: "M. Ambirish",
    district: "Krishnagiri",
  },
  {
    constituencyNo: 56,
    constituencyName: "Thalli",
    candidateName: "G. Suresh",
    district: "Krishnagiri",
  },
  {
    constituencyNo: 57,
    constituencyName: "Palacode",
    candidateName: "R. Gopi",
    district: "Dharmapuri",
  },
  {
    constituencyNo: 58,
    constituencyName: "Pennagaram",
    candidateName: "C. Gajendran",
    district: "Dharmapuri",
  },
  {
    constituencyNo: 59,
    constituencyName: "Dharmapuri",
    candidateName: "M. Sivan",
    district: "Dharmapuri",
  },
  {
    constituencyNo: 60,
    constituencyName: "Pappireddipatti",
    candidateName: "S. Thilagavathi",
    district: "Dharmapuri",
  },
  {
    constituencyNo: 61,
    constituencyName: "Harur",
    candidateName: "K. Rakesh",
    district: "Dharmapuri",
  },
  {
    constituencyNo: 62,
    constituencyName: "Chengam",
    candidateName: "K. Bharathidasan",
    district: "Tiruvannamalai",
  },
  {
    constituencyNo: 63,
    constituencyName: "Tiruvannamalai",
    candidateName: "Arul Arumugam",
    district: "Tiruvannamalai",
  },
  {
    constituencyNo: 64,
    constituencyName: "Kilpennathur",
    candidateName: "D. Raja",
    district: "Tiruvannamalai",
  },
  {
    constituencyNo: 65,
    constituencyName: "Kalasapakkam",
    candidateName: "P. Ezhumalai",
    district: "Tiruvannamalai",
  },
  {
    constituencyNo: 66,
    constituencyName: "Polur",
    candidateName: "R. Abhishek",
    district: "Tiruvannamalai",
  },
  {
    constituencyNo: 67,
    constituencyName: "Arani",
    candidateName: "V. Venkatesh Kumar",
    district: "Tiruvannamalai",
  },
  {
    constituencyNo: 68,
    constituencyName: "Cheyyar",
    candidateName: "Thasi K. Mohan",
    district: "Tiruvannamalai",
  },
  {
    constituencyNo: 69,
    constituencyName: "Vandavasi",
    candidateName: "M. Udhaya Kumar",
    district: "Tiruvannamalai",
  },
  {
    constituencyNo: 70,
    constituencyName: "Gingee",
    candidateName: "B. Chandrasekaran",
    district: "Villupuram",
  },
  {
    constituencyNo: 71,
    constituencyName: "Mailam",
    candidateName: "A. Vijay Niranjan",
    district: "Villupuram",
  },
  {
    constituencyNo: 72,
    constituencyName: "Tindivanam",
    candidateName: "S. Sakthivel",
    district: "Villupuram",
  },
  {
    constituencyNo: 73,
    constituencyName: "Vanur",
    candidateName: "G.P. Suresh",
    district: "Villupuram",
  },
  {
    constituencyNo: 74,
    constituencyName: "Villupuram",
    candidateName: "N. Moganraj",
    district: "Villupuram",
  },
  {
    constituencyNo: 75,
    constituencyName: "Vikravandi",
    candidateName: "A. Vijay Vadivel",
    district: "Villupuram",
  },
  {
    constituencyNo: 76,
    constituencyName: "Tirukkoyilur",
    candidateName: "Vijay R. Barani Balaji",
    district: "Kallakurichi",
  },
  {
    constituencyNo: 77,
    constituencyName: "Ulundurpettai",
    candidateName: "M. Sudhakar",
    district: "Kallakurichi",
  },
  {
    constituencyNo: 78,
    constituencyName: "Rishivandiyam",
    candidateName: "G. Ashok Kumar",
    district: "Kallakurichi",
  },
  {
    constituencyNo: 79,
    constituencyName: "Sankarapuram",
    candidateName: "A. Jegadeesan",
    district: "Kallakurichi",
  },
  {
    constituencyNo: 80,
    constituencyName: "Kallakurichi",
    candidateName: "C. Arulvignesh",
    district: "Kallakurichi",
  },
  {
    constituencyNo: 81,
    constituencyName: "Gangavalli",
    candidateName: "V. Sujatha",
    district: "Salem",
  },
  {
    constituencyNo: 82,
    constituencyName: "Attur",
    candidateName: "R. Selvabharathi",
    district: "Salem",
  },
  {
    constituencyNo: 83,
    constituencyName: "Yercaud",
    candidateName: "J. Lakshmi",
    district: "Salem",
  },
  {
    constituencyNo: 84,
    constituencyName: "Omalur",
    candidateName: "R.V. Athiyaman",
    district: "Salem",
  },
  {
    constituencyNo: 85,
    constituencyName: "Mettur",
    candidateName: "K. Selvam",
    district: "Salem",
  },
  {
    constituencyNo: 86,
    constituencyName: "Edappadi",
    candidateName: "M. Arunkumar",
    district: "Salem",
  },
  {
    constituencyNo: 87,
    constituencyName: "Sankari",
    candidateName: "K. Senthilkumar",
    district: "Salem",
  },
  {
    constituencyNo: 88,
    constituencyName: "Salem West",
    candidateName: "S. Lakshmanan",
    district: "Salem",
  },
  {
    constituencyNo: 89,
    constituencyName: "Salem North",
    candidateName: "K. Sivakumar",
    district: "Salem",
  },
  {
    constituencyNo: 90,
    constituencyName: "Salem South",
    candidateName: "A. Vijay Thamizhan Parthiban",
    district: "Salem",
  },
  {
    constituencyNo: 91,
    constituencyName: "Veerapandi",
    candidateName: "M.S. Palanivel",
    district: "Salem",
  },
  {
    constituencyNo: 92,
    constituencyName: "Rasipuram",
    candidateName: "D. Lokesh Dhanapal",
    district: "Namakkal",
  },
  {
    constituencyNo: 93,
    constituencyName: "Sendamangalam",
    candidateName: "P. Chandrasekar",
    district: "Namakkal",
  },
  {
    constituencyNo: 94,
    constituencyName: "Namakkal",
    candidateName: "C.S. Dilip",
    district: "Namakkal",
  },
  {
    constituencyNo: 95,
    constituencyName: "Paramathi Velur",
    candidateName: "A. Nandhakumar",
    district: "Namakkal",
  },
  {
    constituencyNo: 96,
    constituencyName: "Tiruchengode",
    candidateName: "Dr. K.G. Arunkumar",
    district: "Namakkal",
  },
  {
    constituencyNo: 97,
    constituencyName: "Kumarapalayam",
    candidateName: "C. Vijayalakshmi",
    district: "Namakkal",
  },
  {
    constituencyNo: 98,
    constituencyName: "Erode East",
    candidateName: "M. Vijay Balaji",
    district: "Erode",
  },
  {
    constituencyNo: 99,
    constituencyName: "Erode West",
    candidateName: "K.K. Anand Mohan",
    district: "Erode",
  },
  {
    constituencyNo: 100,
    constituencyName: "Modakkurichi",
    candidateName: "D. Shanmugan",
    district: "Erode",
  },
  {
    constituencyNo: 101,
    constituencyName: "Dharapuram",
    candidateName: "S. Gowri Chitra",
    district: "Tiruppur",
  },
  {
    constituencyNo: 102,
    constituencyName: "Kangayam",
    candidateName: "P. Mani",
    district: "Tiruppur",
  },
  {
    constituencyNo: 103,
    constituencyName: "Perundurai",
    candidateName: "V.P. Arunasalam",
    district: "Erode",
  },
  {
    constituencyNo: 104,
    constituencyName: "Bhavani",
    candidateName: "M.P. Balakrishnan",
    district: "Erode",
  },
  {
    constituencyNo: 105,
    constituencyName: "Anthiyur",
    candidateName: "M. Vijay Venkatesh",
    district: "Erode",
  },
  {
    constituencyNo: 106,
    constituencyName: "Gobichettipalayam",
    candidateName: "K.A. Sengottaiyan",
    district: "Erode",
  },
  {
    constituencyNo: 107,
    constituencyName: "Bhavanisagar",
    candidateName: "V.P. Thamizhselvi",
    district: "Erode",
  },
  {
    constituencyNo: 108,
    constituencyName: "Udhagamandalam",
    candidateName: "R. Ibrahim",
    district: "Nilgiris",
  },
  {
    constituencyNo: 109,
    constituencyName: "Gudalur",
    candidateName: "A. Deep Sah Kishore",
    district: "Nilgiris",
  },
  {
    constituencyNo: 110,
    constituencyName: "Coonoor",
    candidateName: "C. Thangaraj",
    district: "Nilgiris",
  },
  {
    constituencyNo: 111,
    constituencyName: "Mettupalayam",
    candidateName: "N. Sunil Anand",
    district: "Coimbatore",
  },
  {
    constituencyNo: 112,
    constituencyName: "Avinashi",
    candidateName: "S. Kamali",
    district: "Tiruppur",
  },
  {
    constituencyNo: 113,
    constituencyName: "Tiruppur North",
    candidateName: "V. Sathyabama",
    district: "Tiruppur",
  },
  {
    constituencyNo: 114,
    constituencyName: "Tiruppur South",
    candidateName: "S. Balamurugan",
    district: "Tiruppur",
  },
  {
    constituencyNo: 115,
    constituencyName: "Palladam",
    candidateName: "K. Ramkumar",
    district: "Tiruppur",
  },
  {
    constituencyNo: 116,
    constituencyName: "Sulur",
    candidateName: "N.M. Sugumar",
    district: "Coimbatore",
  },
  {
    constituencyNo: 117,
    constituencyName: "Kavundampalayam",
    candidateName: "R.D. Kanimozhi",
    district: "Coimbatore",
  },
  {
    constituencyNo: 118,
    constituencyName: "Coimbatore North",
    candidateName: "V. Sampathkumar",
    district: "Coimbatore",
  },
  {
    constituencyNo: 119,
    constituencyName: "Thondamuthur",
    candidateName: "R. Sathish Raja",
    district: "Coimbatore",
  },
  {
    constituencyNo: 120,
    constituencyName: "Coimbatore South",
    candidateName: "V. Senthilkumar",
    district: "Coimbatore",
  },
  {
    constituencyNo: 121,
    constituencyName: "Singanallur",
    candidateName: "K.S. Sri Giri Prasad",
    district: "Coimbatore",
  },
  {
    constituencyNo: 122,
    constituencyName: "Kinathukadavu",
    candidateName: "K. Vignesh",
    district: "Coimbatore",
  },
  {
    constituencyNo: 123,
    constituencyName: "Pollachi",
    candidateName: "G. Ramanathan",
    district: "Coimbatore",
  },
  {
    constituencyNo: 124,
    constituencyName: "Valparai",
    candidateName: "Dr. A. Sridharan",
    district: "Coimbatore",
  },
  {
    constituencyNo: 125,
    constituencyName: "Udumalaipettai",
    candidateName: "G.K. Sankar",
    district: "Tiruppur",
  },
  {
    constituencyNo: 126,
    constituencyName: "Madathukulam",
    candidateName: "R. Thirumalai",
    district: "Tiruppur",
  },
  {
    constituencyNo: 127,
    constituencyName: "Palani",
    candidateName: "Dr. M. Pravin Kumar",
    district: "Dindigul",
  },
  {
    constituencyNo: 128,
    constituencyName: "Oddanchatram",
    candidateName: "S. Mogan",
    district: "Dindigul",
  },
  {
    constituencyNo: 129,
    constituencyName: "Athoor",
    candidateName: "N. Kalaiselvi",
    district: "Dindigul",
  },
  {
    constituencyNo: 130,
    constituencyName: "Nilakottai",
    candidateName: "R. Aiyanar",
    district: "Dindigul",
  },
  {
    constituencyNo: 131,
    constituencyName: "Natham",
    candidateName: "L.N. Ramesh",
    district: "Dindigul",
  },
  {
    constituencyNo: 132,
    constituencyName: "Dindigul",
    candidateName: "G. Nazir Raja",
    district: "Dindigul",
  },
  {
    constituencyNo: 133,
    constituencyName: "Vedasandur",
    candidateName: "Dr. N. Nagajyothi",
    district: "Dindigul",
  },
  {
    constituencyNo: 134,
    constituencyName: "Aravakurichi",
    candidateName: "P. Karthikeyan",
    district: "Karur",
  },
  {
    constituencyNo: 135,
    constituencyName: "Karur",
    candidateName: "V.P. Mathiyalagan",
    district: "Karur",
  },
  {
    constituencyNo: 136,
    constituencyName: "Krishnarayapuram",
    candidateName: "S. Madhan",
    district: "Karur",
  },
  {
    constituencyNo: 137,
    constituencyName: "Kulithalai",
    candidateName: "G. Balasubramani",
    district: "Karur",
  },
  {
    constituencyNo: 138,
    constituencyName: "Manapparai",
    candidateName: "R. Kathiravan",
    district: "Tiruchirappalli",
  },
  {
    constituencyNo: 139,
    constituencyName: "Srirangam",
    candidateName: "S. Ramesh",
    district: "Tiruchirappalli",
  },
  {
    constituencyNo: 140,
    constituencyName: "Tiruchirappalli West",
    candidateName: "G. Ramamoorthi",
    district: "Tiruchirappalli",
  },
  {
    constituencyNo: 141,
    constituencyName: "Tiruchirappalli East",
    candidateName: "C. Joseph Vijay",
    district: "Tiruchirappalli",
  },
  {
    constituencyNo: 142,
    constituencyName: "Tiruverumbur",
    candidateName: "Navalpattu S. Viji",
    district: "Tiruchirappalli",
  },
  {
    constituencyNo: 143,
    constituencyName: "Lalgudi",
    candidateName: "Ku. Pa. Krishnan",
    district: "Tiruchirappalli",
  },
  {
    constituencyNo: 144,
    constituencyName: "Manachanallur",
    candidateName: "V. Saravanan",
    district: "Tiruchirappalli",
  },
  {
    constituencyNo: 145,
    constituencyName: "Musiri",
    candidateName: "M. Vignesh",
    district: "Tiruchirappalli",
  },
  {
    constituencyNo: 146,
    constituencyName: "Thuraiyur",
    candidateName: "M. Ravishankar",
    district: "Tiruchirappalli",
  },
  {
    constituencyNo: 147,
    constituencyName: "Perambalur",
    candidateName: "K. Sivakumar",
    district: "Perambalur",
  },
  {
    constituencyNo: 148,
    constituencyName: "Kunnam",
    candidateName: "M. Revathi",
    district: "Perambalur",
  },
  {
    constituencyNo: 149,
    constituencyName: "Ariyalur",
    candidateName: "M. Sivakumar",
    district: "Ariyalur",
  },
  {
    constituencyNo: 150,
    constituencyName: "Jayankondam",
    candidateName: "Kavitha G. Rajendran",
    district: "Ariyalur",
  },
  {
    constituencyNo: 151,
    constituencyName: "Tittakudi",
    candidateName: "A. Rajasekar",
    district: "Cuddalore",
  },
  {
    constituencyNo: 152,
    constituencyName: "Vriddhachalam",
    candidateName: "S. Vijay",
    district: "Cuddalore",
  },
  {
    constituencyNo: 153,
    constituencyName: "Neyveli",
    candidateName: "K. Anand",
    district: "Cuddalore",
  },
  {
    constituencyNo: 154,
    constituencyName: "Panruti",
    candidateName: "M. Manikandan",
    district: "Cuddalore",
  },
  {
    constituencyNo: 155,
    constituencyName: "Cuddalore",
    candidateName: "B. Rajkumar",
    district: "Cuddalore",
  },
  {
    constituencyNo: 156,
    constituencyName: "Kurinjipadi",
    candidateName: "D. Rajkumar",
    district: "Cuddalore",
  },
  {
    constituencyNo: 157,
    constituencyName: "Bhuvanagiri",
    candidateName: "T. Magalingam",
    district: "Cuddalore",
  },
  {
    constituencyNo: 158,
    constituencyName: "Chidambaram",
    candidateName: "Dr. N. Bari",
    district: "Cuddalore",
  },
  {
    constituencyNo: 159,
    constituencyName: "Kattumannarkoil",
    candidateName: "S. Srinivasan",
    district: "Cuddalore",
  },
  {
    constituencyNo: 160,
    constituencyName: "Sirkazhi",
    candidateName: "C.S. Gopinath",
    district: "Mayiladuthurai",
  },
  {
    constituencyNo: 161,
    constituencyName: "Mayiladuthurai",
    candidateName: "S.S. Harun Rashid",
    district: "Mayiladuthurai",
  },
  {
    constituencyNo: 162,
    constituencyName: "Poompuhar",
    candidateName: "J. Vijayalayan",
    district: "Mayiladuthurai",
  },
  {
    constituencyNo: 163,
    constituencyName: "Nagapattinam",
    candidateName: "M. Sukumar",
    district: "Nagapattinam",
  },
  {
    constituencyNo: 164,
    constituencyName: "Kilvelur",
    candidateName: "TAP. Senthil Pandian",
    district: "Nagapattinam",
  },
  {
    constituencyNo: 165,
    constituencyName: "Vedaranyam",
    candidateName: "A. Kingsley Gerald",
    district: "Nagapattinam",
  },
  {
    constituencyNo: 166,
    constituencyName: "Thiruthuraipoondi",
    candidateName: "S. Pandian",
    district: "Tiruvarur",
  },
  {
    constituencyNo: 167,
    constituencyName: "Mannargudi",
    candidateName: "UVM. Rajarajan",
    district: "Tiruvarur",
  },
  {
    constituencyNo: 168,
    constituencyName: "Thiruvarur",
    candidateName: "V. Veeramani",
    district: "Tiruvarur",
  },
  {
    constituencyNo: 169,
    constituencyName: "Nannilam",
    candidateName: "S. Prabakaran",
    district: "Tiruvarur",
  },
  {
    constituencyNo: 170,
    constituencyName: "Thiruvidaimarudur",
    candidateName: "S. Prabakaran",
    district: "Thanjavur",
  },
  {
    constituencyNo: 171,
    constituencyName: "Kumbakonam",
    candidateName: "R. Vinoth",
    district: "Thanjavur",
  },
  {
    constituencyNo: 172,
    constituencyName: "Papanasam",
    candidateName: "U. Asarudeen",
    district: "Thanjavur",
  },
  {
    constituencyNo: 173,
    constituencyName: "Thiruvaiyaru",
    candidateName: "M. Manikandan",
    district: "Thanjavur",
  },
  {
    constituencyNo: 174,
    constituencyName: "Thanjavur",
    candidateName: "R. Vijay Saravanan",
    district: "Thanjavur",
  },
  {
    constituencyNo: 175,
    constituencyName: "Orathanadu",
    candidateName: "Dr. K. Aravind",
    district: "Thanjavur",
  },
  {
    constituencyNo: 176,
    constituencyName: "Pattukkottai",
    candidateName: "C. Madhan",
    district: "Thanjavur",
  },
  {
    constituencyNo: 177,
    constituencyName: "Peravurani",
    candidateName: "D. Chandrakandhan",
    district: "Thanjavur",
  },
  {
    constituencyNo: 178,
    constituencyName: "Gandarvakottai",
    candidateName: "N. Subramanian",
    district: "Pudukkottai",
  },
  {
    constituencyNo: 179,
    constituencyName: "Viralimalai",
    candidateName: "P. Murugesan",
    district: "Pudukkottai",
  },
  {
    constituencyNo: 180,
    constituencyName: "Pudukkottai",
    candidateName: "KM. Shafi",
    district: "Pudukkottai",
  },
  {
    constituencyNo: 181,
    constituencyName: "Thirumayam",
    candidateName: "C. Sindhamani",
    district: "Pudukkottai",
  },
  {
    constituencyNo: 182,
    constituencyName: "Alangudi",
    candidateName: "Durai Kandhasami",
    district: "Pudukkottai",
  },
  {
    constituencyNo: 183,
    constituencyName: "Aranthangi",
    candidateName: "J. Mohamed Parvesh",
    district: "Pudukkottai",
  },
  {
    constituencyNo: 184,
    constituencyName: "Karaikudi",
    candidateName: "Dr. T.K. Prabhu",
    district: "Sivaganga",
  },
  {
    constituencyNo: 185,
    constituencyName: "Tiruppattur (Sivaganga)",
    candidateName: "Srinivasa Sethupathi",
    district: "Sivaganga",
  },
  {
    constituencyNo: 186,
    constituencyName: "Sivaganga",
    candidateName: "Kuzhanthai Rani Nachiyar",
    district: "Sivaganga",
  },
  {
    constituencyNo: 187,
    constituencyName: "Manamadurai",
    candidateName: "D. Elangovan",
    district: "Sivaganga",
  },
  {
    constituencyNo: 188,
    constituencyName: "Melur",
    candidateName: "A. Madurai Veeran",
    district: "Madurai",
  },
  {
    constituencyNo: 189,
    constituencyName: "Madurai East",
    candidateName: "S. Karthikeyan",
    district: "Madurai",
  },
  {
    constituencyNo: 190,
    constituencyName: "Sholavandan",
    candidateName: "M.V. Karuppiah",
    district: "Madurai",
  },
  {
    constituencyNo: 191,
    constituencyName: "Madurai North",
    candidateName: "A. Kallanai",
    district: "Madurai",
  },
  {
    constituencyNo: 192,
    constituencyName: "Madurai South",
    candidateName: "J. Joe Peter",
    district: "Madurai",
  },
  {
    constituencyNo: 193,
    constituencyName: "Madurai Central",
    candidateName: "VMS. Musthafa",
    district: "Madurai",
  },
  {
    constituencyNo: 194,
    constituencyName: "Madurai West",
    candidateName: "S.R. Tangapandi",
    district: "Madurai",
  },
  {
    constituencyNo: 195,
    constituencyName: "Thiruparankundram",
    candidateName: "CTR Nirmal Kumar",
    district: "Madurai",
  },
  {
    constituencyNo: 196,
    constituencyName: "Thirumangalam",
    candidateName: "N. Sathishkumar",
    district: "Madurai",
  },
  {
    constituencyNo: 197,
    constituencyName: "Usilampatti",
    candidateName: "M. Vijay",
    district: "Madurai",
  },
  {
    constituencyNo: 198,
    constituencyName: "Andipatti",
    candidateName: "V. Pandi",
    district: "Theni",
  },
  {
    constituencyNo: 199,
    constituencyName: "Periyakulam",
    candidateName: "G. Sabari",
    district: "Theni",
  },
  {
    constituencyNo: 200,
    constituencyName: "Bodinayakanur",
    candidateName: "S. Prakash",
    district: "Theni",
  },
  {
    constituencyNo: 201,
    constituencyName: "Cumbum",
    candidateName: "PLA. Jeganath Misra",
    district: "Theni",
  },
  {
    constituencyNo: 202,
    constituencyName: "Rajapalayam",
    candidateName: "K. Jegadheswari",
    district: "Virudhunagar",
  },
  {
    constituencyNo: 203,
    constituencyName: "Srivilliputhur",
    candidateName: "A. Karthik",
    district: "Virudhunagar",
  },
  {
    constituencyNo: 204,
    constituencyName: "Sattur",
    candidateName: "M. Ajith",
    district: "Virudhunagar",
  },
  {
    constituencyNo: 205,
    constituencyName: "Sivakasi",
    candidateName: "S. Keerthana",
    district: "Virudhunagar",
  },
  {
    constituencyNo: 206,
    constituencyName: "Virudhunagar",
    candidateName: "S.P. Selvam",
    district: "Virudhunagar",
  },
  {
    constituencyNo: 207,
    constituencyName: "Aruppukkottai",
    candidateName: "K. Karthik Kumar",
    district: "Virudhunagar",
  },
  {
    constituencyNo: 208,
    constituencyName: "Tiruchuli",
    candidateName: "S. Samayan",
    district: "Virudhunagar",
  },
  {
    constituencyNo: 209,
    constituencyName: "Paramakudi",
    candidateName: "G. Gopi Rajan",
    district: "Ramanathapuram",
  },
  {
    constituencyNo: 210,
    constituencyName: "Tiruvadanai",
    candidateName: "V.K. Rajeev",
    district: "Ramanathapuram",
  },
  {
    constituencyNo: 211,
    constituencyName: "Ramanathapuram",
    candidateName: "EA. Sagul Hamed",
    district: "Ramanathapuram",
  },
  {
    constituencyNo: 212,
    constituencyName: "Mudukulathur",
    candidateName: "B. Malarvizhi Jeyabala",
    district: "Ramanathapuram",
  },
  {
    constituencyNo: 213,
    constituencyName: "Vilathikulam",
    candidateName: "P. Kasiram",
    district: "Thoothukudi",
  },
  {
    constituencyNo: 214,
    constituencyName: "Thoothukkudi",
    candidateName: "A. Sreenath",
    district: "Thoothukudi",
  },
  {
    constituencyNo: 215,
    constituencyName: "Tiruchendur",
    candidateName: "J. Murugan",
    district: "Thoothukudi",
  },
  {
    constituencyNo: 216,
    constituencyName: "Srivaikuntam",
    candidateName: "G. Saravanan",
    district: "Thoothukudi",
  },
  {
    constituencyNo: 217,
    constituencyName: "Ottapidaram",
    candidateName: "P. Madhan Raja",
    district: "Thoothukudi",
  },
  {
    constituencyNo: 218,
    constituencyName: "Kovilpatti",
    candidateName: "S. Balasubramanian",
    district: "Thoothukudi",
  },
  {
    constituencyNo: 219,
    constituencyName: "Sankarankovil",
    candidateName: "C. Ramarajan",
    district: "Tirunelveli",
  },
  {
    constituencyNo: 220,
    constituencyName: "Vasudevanallur",
    candidateName: "R. Amutha Rani",
    district: "Tirunelveli",
  },
  {
    constituencyNo: 221,
    constituencyName: "Kadayanallur",
    candidateName: "RK. Abdul Jaleel",
    district: "Tirunelveli",
  },
  {
    constituencyNo: 222,
    constituencyName: "Tenkasi",
    candidateName: "A. Rajaprakash",
    district: "Tenkasi",
  },
  {
    constituencyNo: 223,
    constituencyName: "Alangulam",
    candidateName: "V. Vipin Chakravarthy",
    district: "Tenkasi",
  },
  {
    constituencyNo: 224,
    constituencyName: "Tirunelveli",
    candidateName: "R.S. Murugan",
    district: "Tirunelveli",
  },
  {
    constituencyNo: 225,
    constituencyName: "Ambasamudram",
    candidateName: "S. Rajagopal",
    district: "Tirunelveli",
  },
  {
    constituencyNo: 226,
    constituencyName: "Palayamkottai",
    candidateName: "S. Maria John",
    district: "Tirunelveli",
  },
  {
    constituencyNo: 227,
    constituencyName: "Nanguneri",
    candidateName: "Reddiyarpatti Narayanan",
    district: "Tirunelveli",
  },
  {
    constituencyNo: 228,
    constituencyName: "Radhapuram",
    candidateName: "K. Sathis Christopher",
    district: "Tirunelveli",
  },
  {
    constituencyNo: 229,
    constituencyName: "Kanyakumari",
    candidateName: "S.R. Madhavan",
    district: "Kanyakumari",
  },
  {
    constituencyNo: 230,
    constituencyName: "Nagercoil",
    candidateName: "G. Berwin Kings",
    district: "Kanyakumari",
  },
  {
    constituencyNo: 231,
    constituencyName: "Colachel",
    candidateName: "Dr. Prem Alex Lawrence",
    district: "Kanyakumari",
  },
  {
    constituencyNo: 232,
    constituencyName: "Padmanabhapuram",
    candidateName: "S. Krishnakumar",
    district: "Kanyakumari",
  },
  {
    constituencyNo: 233,
    constituencyName: "Vilavancode",
    candidateName: "K. Michael Kumar",
    district: "Kanyakumari",
  },
  {
    constituencyNo: 234,
    constituencyName: "Killiyoor",
    candidateName: "S. Sivin",
    district: "Kanyakumari",
  },
];
